<?php
return array (
  1 => 
  array (
    'id' => '1',
    'catid' => '9',
    'typeid' => '0',
    'title' => '高档指纹02-高贵金',
    'style' => '',
    'thumb' => 'http://www.rixiang-fj.com/uploadfile/2014/0706/20140706015128724.jpg',
    'keywords' => '指纹',
    'description' => '',
    'posids' => '0',
    'url' => 'http://www.rixiang-fj.com/index.php?m=content&c=index&a=show&catid=12&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'sinfey',
    'inputtime' => '1404582680',
    'updatetime' => '1404582753',
    'hitsid' => 'c-3-1',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  2 => 
  array (
    'id' => '2',
    'catid' => '9',
    'typeid' => '0',
    'title' => '高档指纹03-典雅银',
    'style' => '',
    'thumb' => 'http://www.rixiang-fj.com/uploadfile/2014/0706/20140706015405604.jpg',
    'keywords' => '指纹 高贵',
    'description' => '',
    'posids' => '0',
    'url' => 'http://www.rixiang-fj.com/index.php?m=content&c=index&a=show&catid=12&id=2',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'sinfey',
    'inputtime' => '1404582783',
    'updatetime' => '1404582852',
    'hitsid' => 'c-3-2',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  3 => 
  array (
    'id' => '3',
    'catid' => '18',
    'typeid' => '0',
    'title' => 'EM苹果-Y',
    'style' => '',
    'thumb' => 'http://www.rixiang-fj.com/uploadfile/2014/0706/20140706020220737.jpg',
    'keywords' => '苹果',
    'description' => '',
    'posids' => '0',
    'url' => 'http://www.rixiang-fj.com/index.php?m=content&c=index&a=show&catid=18&id=3',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'sinfey',
    'inputtime' => '1404583322',
    'updatetime' => '1404583343',
    'hitsid' => 'c-3-3',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>